import type {
  Department,
  DeptKey,
  IndustryKey,
  Solution,
  SolutionType,
} from "@/types/diagnostic";

export const DEPTS: Record<DeptKey, Department> = {
  sales: {
    key: "sales",
    name: "销售",
    fill: "#ddeeff",
    stroke: "#4a90d9",
    text: "#1a5c9e",
    pains: [
      "客户问了没人跟，生意跑掉",
      "做报价单很慢",
      "不知道现在卖得怎样",
      "不知道新客户从哪里来",
    ],
  },
  market: {
    key: "market",
    name: "市场 / 广告",
    fill: "#ddf5e8",
    stroke: "#2e9e5e",
    text: "#1a6e3a",
    pains: [
      "写贴文太慢，赶不上发",
      "整理广告数据很花时间",
      "搞活动没有固定步骤",
      "每个平台都要重复发一次",
    ],
  },
  service: {
    key: "service",
    name: "客服",
    fill: "#fff3d8",
    stroke: "#c88a18",
    text: "#8a5a08",
    pains: [
      "一样的问题要答很多次",
      "客户投诉容易忘记跟进",
      "回客户太慢，客人不开心",
      "常见问题没有地方集中放",
    ],
  },
  ops: {
    key: "ops",
    name: "日常运作",
    fill: "#ede8ff",
    stroke: "#7050c8",
    text: "#4a2e9e",
    pains: [
      "每天的工作步骤靠人记，容易漏",
      "重要数据散在很多地方",
      "不知道同事做到哪里了",
      "各部门数据不通",
    ],
  },
  stock: {
    key: "stock",
    name: "库存",
    fill: "#ffe8d8",
    stroke: "#c86020",
    text: "#8a3a08",
    pains: [
      "点货靠人数，容易错",
      "不知道什么时候要进货",
      "进货出货没有记录",
      "库存和销量对不上",
    ],
  },
  finance: {
    key: "finance",
    name: "财务 / 钱",
    fill: "#ffe0ee",
    stroke: "#c82868",
    text: "#8a1848",
    pains: [
      "记账靠人写，容易漏",
      "月底对账要做好几天",
      "不知道钱从哪里漏走",
      "报销批得很慢",
    ],
  },
  hr: {
    key: "hr",
    name: "人事",
    fill: "#e8f8d8",
    stroke: "#4a9820",
    text: "#2a6808",
    pains: [
      "看简历太花时间，好的漏掉",
      "员工资料散在各处",
      "整理打卡记录很花时间",
      "新员工入职没有固定流程",
    ],
  },
  mgmt: {
    key: "mgmt",
    name: "老板 / 管理",
    fill: "#eeeeea",
    stroke: "#888878",
    text: "#444438",
    pains: [
      "各部门数据要人工整理",
      "看不到公司现在怎样",
      "做决定没有数据可以看",
      "每周报告要人手动做",
    ],
  },
};

export const DEPT_ORDER: DeptKey[] = [
  "sales",
  "market",
  "service",
  "ops",
  "stock",
  "finance",
  "hr",
  "mgmt",
];

export const IND_EXTRA: Partial<Record<IndustryKey, Partial<Record<DeptKey, string>>>> = {
  fnb: {
    sales: "找新客贵，订位全靠人接",
    market: "节日活动贴文赶不上",
    service: "忙的时候投诉顾不上",
    ops: "几间店的数据看不在一起",
    stock: "食材浪费多，补货靠感觉",
    finance: "几个收钱方式对账很乱",
    hr: "兼职员工排班难搞",
    mgmt: "每间店每天生意看不清楚",
  },
  retail: {
    sales: "网店和实体店库存对不上，卖多了",
    market: "新货文案写不出来",
    service: "退换货步骤多，客人不开心",
    ops: "几个平台搞促销要改很久",
    stock: "好卖的断货，不好卖的堆着",
    finance: "每个平台佣金和退款对账很乱",
    hr: "旺季请临时工，很难管",
    mgmt: "几个平台的销量看不在一起",
  },
  education: {
    sales: "试听之后跟得太慢",
    market: "招生文案写不完",
    service: "学生一样的问题问很多次",
    ops: "排课和看出席很花时间",
    stock: "教材教具库存很乱",
    finance: "分期学费难跟",
    hr: "兼职老师排课很难协调",
    mgmt: "招生的每一步数据看不清楚",
  },
  healthcare: {
    sales: "新病人预约步骤太多",
    market: "医疗内容写不出来",
    service: "复诊提醒要人打电话",
    ops: "诊室和排班很难协调",
    stock: "药品到期日很难管",
    finance: "保险理赔和自费账很乱",
    hr: "医护人员排班很难",
    mgmt: "看诊人数和收入很慢才看到",
  },
  professional: {
    sales: "大客户跟进周期太长",
    market: "专业内容要好又要快，做不到",
    service: "客户常常问做到哪里了",
    ops: "几个项目一起做，很累",
    stock: "软件到期没人提醒",
    finance: "开账单和催款很慢",
    hr: "要请好人才，时间太长",
    mgmt: "每个项目赚亏看不清楚",
  },
  manufacturing: {
    sales: "做报价单和跟进都很慢",
    market: "卖给公司的宣传很少",
    service: "售后处理太慢",
    ops: "生产进度和交货日难跟",
    stock: "原料库存很难算准",
    finance: "生产成本和利润很难算",
    hr: "车间排班和表现很难算",
    mgmt: "产能和准时交货看不清楚",
  },
  realestate: {
    sales: "询问很多，跟不过来",
    market: "房源文案写太慢",
    service: "看房预约和跟进很乱",
    ops: "成交进度和合同文件很乱",
    stock: "房源资料更新慢或错",
    finance: "佣金算错分错",
    hr: "经纪人业绩和目标难跟",
    mgmt: "整体成交和收入看不清楚",
  },
};

export const IND_LABELS: Record<IndustryKey, string> = {
  general: "",
  fnb: "餐饮",
  retail: "零售 / 网店",
  education: "教育",
  healthcare: "医疗",
  professional: "专业服务",
  manufacturing: "工厂",
  realestate: "房地产",
  other: "",
};

export const INDUSTRY_OPTIONS: Array<{ value: IndustryKey; label: string }> = [
  { value: "general", label: "请选择行业 →" },
  { value: "fnb", label: "餐饮 / F&B" },
  { value: "retail", label: "零售 / 网店" },
  { value: "education", label: "教育 / 补习" },
  { value: "healthcare", label: "医疗 / 健康" },
  { value: "professional", label: "专业服务" },
  { value: "manufacturing", label: "工厂 / 制造" },
  { value: "realestate", label: "房地产 / 中介" },
  { value: "other", label: "其他（自己写）" },
];

export const PAIN_SOLUTIONS: Record<DeptKey, Solution[]> = {
  sales: [
    {
      name: "客户跟进提醒",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "自动记下每个客户，到时间提醒你跟进，不会漏掉",
      outcome: "漏单率从 20% 降到 2% · 每月多抓 3–5 单",
      impact: 9,
      effort: 3,
      hoursSavedPerMonth: 12,
      tags: ["跟进", "客户", "漏单", "询盘", "follow up", "联络"],
    },
    {
      name: "一键报价单",
      type: "ai",
      tool: "直接用 Claude",
      desc: "把报价方式告诉 Claude，输入客户要什么，10 秒写好报价单",
      outcome: "报价时间从 30 分钟变 1 分钟",
      impact: 7,
      effort: 1,
      hoursSavedPerMonth: 16,
      tags: ["报价", "报价单", "quotation", "价格"],
    },
    {
      name: "销售情况一页看",
      type: "full",
      tool: "Vibe Coding 系统",
      desc: "一页看到每个客户跟到哪里，团队卖多少",
      outcome: "随时知道卖了多少 · 不用等月底报告",
      impact: 7,
      effort: 7,
      hoursSavedPerMonth: 8,
      tags: ["销售", "数据", "看板", "dashboard", "成交"],
    },
    {
      name: "客户来源记录",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "自动记下客户从哪里来，月底看哪个渠道最好",
      outcome: "找出最赚钱的渠道 · 广告预算省 30%",
      impact: 6,
      effort: 3,
      hoursSavedPerMonth: 4,
      tags: ["渠道", "来源", "新客", "广告"],
    },
  ],
  market: [
    {
      name: "AI 多平台写贴文",
      type: "ai",
      tool: "直接用 Claude",
      desc: "一个主题，Claude 自动写 Facebook/IG/WhatsApp 几个版本，直接复制发",
      outcome: "一个贴文从 2 小时变 15 分钟",
      impact: 8,
      effort: 1,
      hoursSavedPerMonth: 20,
      tags: ["贴文", "文案", "facebook", "instagram", "ig", "发文", "社交"],
    },
    {
      name: "广告数据自动日报",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "每天自动整理各平台广告数据，做成图表发到你的邮箱",
      outcome: "每天省 1 小时整理数据",
      impact: 6,
      effort: 4,
      hoursSavedPerMonth: 22,
      tags: ["广告", "数据", "日报", "报表", "facebook ads", "google ads"],
    },
    {
      name: "活动计划生成器",
      type: "ai",
      tool: "直接用 Claude",
      desc: "告诉 Claude 要做什么活动和预算，自动给你完整步骤和时间表",
      outcome: "活动策划从 3 天变 2 小时",
      impact: 5,
      effort: 1,
      hoursSavedPerMonth: 6,
      tags: ["活动", "策划", "计划", "promotion", "活动计划"],
    },
    {
      name: "多平台发贴助手",
      type: "ai",
      tool: "直接用 Claude",
      desc: "一份内容，Claude 改写成每个平台的版本，省 90% 时间",
      outcome: "发贴时间省 90%",
      impact: 7,
      effort: 1,
      hoursSavedPerMonth: 16,
      tags: ["发贴", "平台", "跨平台", "重复"],
    },
  ],
  service: [
    {
      name: "AI 快速回复",
      type: "ai",
      tool: "直接用 Claude",
      desc: "把客户问题丢给 Claude，3 秒写好回复，看过就发",
      outcome: "回复速度从 30 分钟变 3 秒",
      impact: 8,
      effort: 1,
      hoursSavedPerMonth: 25,
      tags: ["回复", "回答", "问题", "客户", "重复"],
    },
    {
      name: "客诉追踪板",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "每个投诉都有人跟、有时间、做完没有，没做完自动提醒",
      outcome: "投诉漏跟从 15% 降到 0%",
      impact: 8,
      effort: 3,
      hoursSavedPerMonth: 8,
      tags: ["投诉", "客诉", "complaint", "追踪", "跟进"],
    },
    {
      name: "回复速度报表",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "自动算客服多久回一次，每周看报告找出问题",
      outcome: "找出慢的地方 · 平均回复速度提升 50%",
      impact: 5,
      effort: 3,
      hoursSavedPerMonth: 4,
      tags: ["回复", "速度", "响应", "报表", "KPI"],
    },
    {
      name: "AI 问答知识库",
      type: "ai",
      tool: "直接用 Claude",
      desc: "把常见问题给 Claude，客服用中文直接问，马上给答案",
      outcome: "新客服上手时间从 1 个月变 3 天",
      impact: 7,
      effort: 2,
      hoursSavedPerMonth: 18,
      tags: ["faq", "常见问题", "知识库", "答案", "培训"],
    },
  ],
  ops: [
    {
      name: "工作步骤清单",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "把所有工作步骤变成手机清单，做了打勾，不用靠记",
      outcome: "出错率从 10% 降到 1%",
      impact: 7,
      effort: 3,
      hoursSavedPerMonth: 10,
      tags: ["sop", "步骤", "流程", "清单", "checklist"],
    },
    {
      name: "每日数据自动日报",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "每天自动收集各部门数字，发到群组，不用等人整理",
      outcome: "每天省 2 小时整理报告",
      impact: 7,
      effort: 4,
      hoursSavedPerMonth: 40,
      tags: ["数据", "日报", "报表", "dashboard", "汇总"],
    },
    {
      name: "团队任务追踪板",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "每件事谁做、几时完，快到期自动提醒",
      outcome: "任务漏做从 20% 降到 3%",
      impact: 6,
      effort: 3,
      hoursSavedPerMonth: 6,
      tags: ["任务", "task", "追踪", "进度", "deadline"],
    },
    {
      name: "公司数据一页看",
      type: "full",
      tool: "Vibe Coding 系统",
      desc: "各部门数据集中一页，老板随时可以看",
      outcome: "不用再等人汇报 · 每周省 4 小时",
      impact: 8,
      effort: 8,
      hoursSavedPerMonth: 16,
      tags: ["看板", "dashboard", "数据", "统一", "整合"],
    },
  ],
  stock: [
    {
      name: "进出货记录系统",
      type: "full",
      tool: "Vibe Coding 系统",
      desc: "进货出货都记下来，库存数自动算，不用再人工点货",
      outcome: "盘点时间从 1 天变 1 小时",
      impact: 9,
      effort: 7,
      hoursSavedPerMonth: 24,
      tags: ["库存", "盘点", "进出货", "stock", "inventory"],
    },
    {
      name: "库存不够自动提醒",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "设定最低数量，少过就自动发邮件提醒，不用自己盯",
      outcome: "断货次数从每月 5 次降到 0 次",
      impact: 8,
      effort: 3,
      hoursSavedPerMonth: 6,
      tags: ["补货", "库存", "提醒", "reorder", "断货"],
    },
    {
      name: "进出货流水记录",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "每次进出货自动记时间，月底对账有完整记录",
      outcome: "月底对账从 2 天变 2 小时",
      impact: 6,
      effort: 3,
      hoursSavedPerMonth: 12,
      tags: ["进货", "出货", "记录", "流水"],
    },
    {
      name: "库存 x 销量一页看",
      type: "full",
      tool: "Vibe Coding 系统",
      desc: "库存和销量连在一起看，什么断货、什么堆着，一眼看到",
      outcome: "滞销库存减 30% · 爆款不再断货",
      impact: 9,
      effort: 8,
      hoursSavedPerMonth: 12,
      tags: ["库存", "销量", "滞销", "爆款", "看板"],
    },
  ],
  finance: [
    {
      name: "收支记录系统",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "收钱出钱一录入就分类，月底一下就出报告",
      outcome: "记账时间省 70%",
      impact: 8,
      effort: 4,
      hoursSavedPerMonth: 20,
      tags: ["记账", "收支", "入账", "分类"],
    },
    {
      name: "月底对账自动报表",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "自动整理所有账，月底对账从几天变几分钟",
      outcome: "月底对账从 3 天变 2 小时",
      impact: 9,
      effort: 4,
      hoursSavedPerMonth: 24,
      tags: ["对账", "月底", "账目", "报表", "reconciliation"],
    },
    {
      name: "财务情况一页看",
      type: "full",
      tool: "Vibe Coding 系统",
      desc: "每条业务赚多少亏多少，一目了然",
      outcome: "找出漏钱点 · 利润提升 5–15%",
      impact: 9,
      effort: 8,
      hoursSavedPerMonth: 10,
      tags: ["财务", "利润", "盈亏", "看板", "漏钱"],
    },
    {
      name: "报销审批系统",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "员工申请报销，系统自动通知老板批，进度看得到",
      outcome: "报销审批从 5 天变 1 天",
      impact: 5,
      effort: 3,
      hoursSavedPerMonth: 6,
      tags: ["报销", "审批", "claim", "approval"],
    },
  ],
  hr: [
    {
      name: "AI 简历筛选",
      type: "ai",
      tool: "直接用 Claude",
      desc: "把工作要求和简历给 Claude，自动打分排序，10 分钟看 100 份",
      outcome: "看简历时间从 8 小时变 10 分钟",
      impact: 8,
      effort: 1,
      hoursSavedPerMonth: 16,
      tags: ["简历", "招聘", "resume", "cv", "筛选"],
    },
    {
      name: "员工资料系统",
      type: "full",
      tool: "Vibe Coding 系统",
      desc: "所有员工资料集中一个地方，搜索就找得到，更新也方便",
      outcome: "找员工资料时间省 90%",
      impact: 6,
      effort: 7,
      hoursSavedPerMonth: 8,
      tags: ["员工", "资料", "hr", "档案"],
    },
    {
      name: "打卡自动统计",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "打卡数据自动算，月底直接出考勤报告，不用人工整理",
      outcome: "考勤整理从 2 天变 30 分钟",
      impact: 7,
      effort: 3,
      hoursSavedPerMonth: 16,
      tags: ["打卡", "考勤", "attendance", "出勤"],
    },
    {
      name: "新员工入职清单",
      type: "light",
      tool: "Claude Code 小工具",
      desc: "每个入职步骤都记下，谁做、几时做、做到哪里，都看得到",
      outcome: "入职步骤漏做从 30% 降到 0%",
      impact: 5,
      effort: 3,
      hoursSavedPerMonth: 4,
      tags: ["入职", "onboarding", "新员工", "清单"],
    },
  ],
  mgmt: [
    {
      name: "AI 数据摘要",
      type: "ai",
      tool: "直接用 Claude",
      desc: "各部门把数据给 Claude，自动写成 3 分钟看完的摘要",
      outcome: "看完所有部门报告从 2 小时变 3 分钟",
      impact: 7,
      effort: 1,
      hoursSavedPerMonth: 16,
      tags: ["摘要", "summary", "报告", "整合"],
    },
    {
      name: "公司一页看板",
      type: "full",
      tool: "Vibe Coding 系统",
      desc: "所有部门重要数字一页看完，自动更新，不用等人报告",
      outcome: "决策速度提升 5 倍 · 不用再等周报",
      impact: 10,
      effort: 9,
      hoursSavedPerMonth: 20,
      tags: ["看板", "dashboard", "kpi", "公司数据"],
    },
    {
      name: "数据分析报告",
      type: "ai",
      tool: "直接用 Claude",
      desc: "把过去的数据给 Claude，自动分析趋势，给你带结论的报告",
      outcome: "分析报告从 1 星期变 30 分钟",
      impact: 8,
      effort: 1,
      hoursSavedPerMonth: 20,
      tags: ["分析", "趋势", "报告", "决策", "analysis"],
    },
    {
      name: "AI 自动周报",
      type: "ai",
      tool: "直接用 Claude",
      desc: "各部门输入数字，Claude 自动整合，出标准周报",
      outcome: "做周报时间从半天变 15 分钟",
      impact: 6,
      effort: 2,
      hoursSavedPerMonth: 8,
      tags: ["周报", "报告", "weekly", "总结"],
    },
  ],
};

export const SOL_TYPE_LABEL: Record<SolutionType, string> = {
  ai: "不用写代码 · 直接用 Claude",
  light: "小工具 · Claude 帮你做",
  full: "完整系统 · Claude 帮你做",
};

export const SOL_TYPE_STYLE: Record<SolutionType, { bg: string; border: string; text: string }> = {
  ai: { bg: "#eaf7f0", border: "rgba(26,122,74,0.25)", text: "#1a7a4a" },
  light: { bg: "#ddeeff", border: "rgba(74,144,217,0.35)", text: "#1a5c9e" },
  full: { bg: "#fdf6e3", border: "rgba(212,160,23,0.3)", text: "#d4a017" },
};

export function getPainsForDept(industry: IndustryKey, dept: DeptKey): string[] {
  const base = DEPTS[dept].pains;
  const extra = IND_EXTRA[industry]?.[dept];
  return extra ? [extra, ...base.slice(1)] : base;
}
